### PR TITLE
Removed `make compile` and pinning deps - use latest versions instead. Plus fix pandas FutureWarning

### PR DESCRIPTION
**Pull request by DBCerigo**
What is says on the tin. 

I was seeing this warning when using `kotsu` in that `sktime` PR. 

- [x] Have you added to CHANGELOG.md for this PR?

### CODE REVIEW

**Comment by DBCerigo** [comment]
@ali-tny this has got me thinking, do we need to pin the deps into a txt, given this is a package not a project? Or even should we _not_ be pinning the deps because it's a package?

**Review by ali-tny — APPROVED** [review]
re pinning: i think not pinning doesn't solve the main problem, which is that we say in the `setup.py` that different versions are compatible but we don't actually test it. not pinning just means there's an element of randomness to the test step: has a dependency been updated that's added a problem at the same time as your code change? which is separate to the main value of the tests which is to check your code changes haven't introduced a bug. so i think we should keep pinning

options to actually solve the problem:
- test against eg various different pandas versions in testing (this could mean a lot of tests though which might be painful)
- get one of those services that alerts you when new versions of your dependencies are released that auto make prs -> runs tests against the latest version at least

not a huge deal rn though i think

**Comment by ali-tny** [comment]
re the above: didn't realise the extra pain due to testing against different python versions. think its a decent idea to just drop the pins as suggested 👍

**Comment by DBCerigo** [comment]
> re the above: didn't realise the extra pain due to testing against different python versions. think its a decent idea to just drop the pins as suggested +1

@ali-tny: now implemented. 

Something seemingly mad going on: see https://github.com/datavaluepeople/kotsu/runs/8097037101?check_suite_focus=true for an empty commit PR which now fails (grim) as `mypy` checks that versioneer file. I tried loads of variations on trying to fix it, no luck. In the end I added an explicit `# mypy: ignore-errors` to the file. 

Now ready for review and can merge if approve.

**Review by ali-tny — APPROVED** [review]

**Pull request merged**
